# Generated by Django 5.2.14 on 2026-06-02 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_id", models.CharField(blank=True, max_length=255, null=True)),
                ("actor_rol", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesión"),
                            ("MARCACION", "Marcación"),
                            ("NOVEDAD_CREADA", "Novedad creada"),
                            ("NOVEDAD_APROBADA", "Novedad aprobada"),
                            ("TURNO_CAMBIADO", "Turno cambiado"),
                            ("CONFIG_CAMBIADA", "Configuración cambiada"),
                            ("EXPORTACION_DATOS", "Exportación de datos"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entidad", models.CharField(max_length=100)),
                ("entidad_id", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "db_table": "audit_log",
                "ordering": ("-created_at",),
            },
        ),
    ]
