# Generated by Django 5.2.14 on 2026-06-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0002_audit_log_append_only_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Inicio de sesión"),
                    ("MARCACION", "Marcación"),
                    ("NOVEDAD_CREADA", "Novedad creada"),
                    ("NOVEDAD_APROBADA", "Novedad aprobada"),
                    ("TURNO_CAMBIADO", "Turno cambiado"),
                    ("CONFIG_CAMBIADA", "Configuración cambiada"),
                    ("EXPORTACION_DATOS", "Exportación de datos"),
                    ("EMPLEADO_CREADO", "Empleado creado"),
                    (
                        "CONSENTIMIENTO_REGISTRADO",
                        "Consentimiento Habeas Data registrado",
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
