# Generated by Django 5.2.14 on 2026-06-03 16:30

import django.db.models.deletion
import novedades.models
import novedades.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Novedad",
            fields=[
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INCAPACIDAD", "Incapacidad"),
                            ("PERMISO", "Permiso"),
                            ("VACACIONES", "Vacaciones"),
                            ("PROBLEMA", "Problema reportado"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novedades",
                        to="personal.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Novedad",
                "verbose_name_plural": "Novedades",
                "db_table": "novedad",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SoporteNovedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        storage=novedades.storage.PrivateMediaStorage(),
                        upload_to=novedades.models._ruta_soporte,
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("tipo_mime", models.CharField(max_length=100)),
                ("tamano_bytes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "novedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soportes",
                        to="novedades.novedad",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soportes_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soporte de novedad",
                "verbose_name_plural": "Soportes de novedad",
                "db_table": "soporte_novedad",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="novedad",
            index=models.Index(
                fields=["empleado", "estado"], name="novedad_emplead_798a0d_idx"
            ),
        ),
    ]
