# Generated by Django 5.2.14 on 2026-06-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizacion", "0001_initial"),
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaFestivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                ("descripcion", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Día festivo",
                "verbose_name_plural": "Días festivos",
                "db_table": "dia_festivo",
                "ordering": ("fecha",),
            },
        ),
        migrations.CreateModel(
            name="ParametrosLaborales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("inicio_jornada_nocturna", models.TimeField()),
                ("fin_jornada_nocturna", models.TimeField()),
                (
                    "horas_jornada_ordinaria_diaria",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "porcentaje_extra_diurna",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porcentaje_extra_nocturna",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porcentaje_recargo_nocturno",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porcentaje_dominical_festivo",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("vigente_desde", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Parámetros laborales",
                "verbose_name_plural": "Parámetros laborales",
                "db_table": "parametros_laborales",
                "ordering": ("-vigente_desde", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nombre", models.CharField(max_length=120)),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("cruza_medianoche", models.BooleanField(default=False)),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos",
                        to="organizacion.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "db_table": "turno",
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="ResumenJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_entrada", models.DateTimeField(blank=True, null=True)),
                ("hora_salida", models.DateTimeField(blank=True, null=True)),
                (
                    "horas_ordinarias",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "horas_extra_diurnas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "horas_extra_nocturnas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "horas_recargo_nocturno",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "horas_dominical_festivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("tardanza_minutos", models.PositiveIntegerField(default=0)),
                ("salida_temprana_minutos", models.PositiveIntegerField(default=0)),
                ("calculado_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resumenes_jornada",
                        to="personal.empleado",
                    ),
                ),
                (
                    "parametros",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="turnos.parametroslaborales",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="turnos.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen de jornada",
                "verbose_name_plural": "Resúmenes de jornada",
                "db_table": "resumen_jornada",
                "ordering": ("-fecha",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empleado", "fecha"), name="uniq_resumen_empleado_fecha"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AsignacionTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_turno",
                        to="personal.empleado",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="turnos.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de turno",
                "verbose_name_plural": "Asignaciones de turno",
                "db_table": "asignacion_turno",
                "ordering": ("-fecha_inicio",),
                "indexes": [
                    models.Index(
                        fields=["empleado", "fecha_inicio"],
                        name="asignacion__emplead_28aa61_idx",
                    )
                ],
            },
        ),
    ]
