# Generated by Django 5.2.14 on 2026-06-02 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nombre", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresa",
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "ciudad",
                    models.CharField(
                        choices=[
                            ("MEDELLIN", "Medellín"),
                            ("CALI", "Cali"),
                            ("BOGOTA", "Bogotá"),
                            ("BARRANQUILLA", "Barranquilla"),
                        ],
                        max_length=20,
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("radio_metros", models.PositiveIntegerField(default=100)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sedes",
                        to="organizacion.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "db_table": "sede",
                "ordering": ("empresa__nombre", "nombre"),
            },
        ),
    ]
