# Generated by Django 5.2.14 on 2026-06-03 00:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizacion", "0001_initial"),
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marcacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        max_length=10,
                    ),
                ),
                (
                    "timestamp_servidor",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("timestamp_dispositivo", models.DateTimeField(blank=True, null=True)),
                (
                    "minuto_marcacion",
                    models.DateTimeField(db_index=True, editable=False),
                ),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("fuera_de_sede", models.BooleanField(default=False)),
                (
                    "distancia_metros",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("es_offline", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corrige_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correcciones",
                        to="marcacion.marcacion",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marcaciones",
                        to="personal.empleado",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marcaciones",
                        to="organizacion.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marcación",
                "verbose_name_plural": "Marcaciones",
                "db_table": "marcacion",
                "ordering": ("-timestamp_servidor",),
                "indexes": [
                    models.Index(
                        fields=["empleado", "tipo", "timestamp_servidor"],
                        name="marcacion_emplead_86bfe9_idx",
                    ),
                    models.Index(
                        fields=["sede", "timestamp_servidor"],
                        name="marcacion_sede_id_dcd0c7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("corrige_a__isnull", True)),
                        fields=("empleado", "tipo", "minuto_marcacion"),
                        name="uniq_marcacion_empleado_tipo_minuto",
                    )
                ],
            },
        ),
    ]
