# Generated by Django 5.2.14 on 2026-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marcacion", "0002_marcacion_inmutable_trigger"),
        ("organizacion", "0001_initial"),
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marcacion",
            name="qr_jti",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="marcacion",
            name="revisar_offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marcacion",
            name="timestamp_qr",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="marcacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("qr_jti__isnull", False)),
                fields=("empleado", "qr_jti"),
                name="uniq_marcacion_empleado_qrjti",
            ),
        ),
    ]
